project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Alba Refoyo Martinez
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: My research
    right:
      - icon: linkedin
        href: https://dk.linkedin.com/in/albarefoyo
        aria-label: LinkedIn 
      - icon: github
        href: https://github.com/albarema
        aria-label: GitHub
format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: false
